export { default as AboutPage } from "./AboutPage";
export { default as CompaniesPage } from "./CompaniesPage";
export { default as ErrorPage } from "./ErrorPage";
export { default as HomePage } from "./HomePage";
export { default as ProfileUserPage } from "./ProfileUserPage";
export { default as RegisterPage } from "./RegisterPage";
export { default as AdminHome } from "./admin/AdminHome";
export { default as CompaniesAdmin } from "./admin/CompaniesAdmin";
export { default as NewOrEditCompany } from "./admin/NewOrEditCompany";
export { default as AllCompanies } from "./companies/AllCompanies";
export { default as SingleCompany } from "./companies/SingleCompany";
export * from "./index";
export { default as ProtectedAdminRoute } from "./protectedRoutes/ProtectedAdminRoute";
export { default as ProtectedUserRoutes } from "./protectedRoutes/ProtectedUserRoutes";
